version: '3'
services:
  postgres:
    image: postgres:14
    networks:
      - net
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - $PWD/postgres-data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:lts
    platform: linux/amd64
    ports:
      - 9001:9000
      - 9092:9092
    networks:
      - net
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres

networks:
  net: