version: '3'
services:
  jenkins:
    image: jenkins/docker
    build:
      context: dockerjenkins
      dockerfile: Dockerfile
    container_name: jenkins_master
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    privileged: true
    user: root
    volumes:
      - /home/ubuntu/jenkins_home:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
networks:
    net: