version: '3'
services:
  jenkins2:
    image: jenkins/jenkins 
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins_master
    privileged: true
    user: root
    volumes:
      - /home/ubuntu/jenkins_home:/var/jenkins_home 
    networks:
      - net
networks:
  net: 